### ISSUE TITLE
GMaps Scrapper

### ISSUE THREAD

**Issue by hmehmood121** [padmanabhan-s/scraping-google-map#1]

**Comment by ayushkarn2020** [comment]
Error was there ERROR occured at clicking net button

**Comment by padmanabhan-s** [comment]
Please use an exact link of google map
Example

"https://www.google.com/search?sa=X&rlz=1C1CHBF_enIN844IN844&sz=0&biw=1036&bih=529&tbs=lf:1,lf_ui:9&tbm=lcl&q=restaurants+in+papua+new+guinea&rflfq=1&num=10&ved=2ahUKEwinh4ngttHwAhV_7XMBHTlIBVAQjGp6BAgiEGc&cshid=1621278964391616"
