### ISSUE TITLE
Is this a dead project? Please respond, developer!

### ISSUE THREAD

**Issue by ghost** [padmanabhan-s/scraping-google-map#2]
I tried the firefox script. In what format does it want the link? Can you PLEASE give an example of a link to enter? What kind of link does the script work with?

**Comment by Hafizvj** [comment]
I tried both and both seems dead

**Comment by ghost** [comment]
Eeeeeyyup.

**Comment by padmanabhan-s** [comment]
sorry for the late reply. 
please use this example link

"https://www.google.com/search?sa=X&rlz=1C1CHBF_enIN844IN844&sz=0&biw=1036&bih=529&tbs=lf:1,lf_ui:9&tbm=lcl&q=restaurants+in+papua+new+guinea&rflfq=1&num=10&ved=2ahUKEwinh4ngttHwAhV_7XMBHTlIBVAQjGp6BAgiEGc&cshid=1621278964391616"

**Comment by Hafizvj** [comment]
What do you mean by "Enter File name" ???

**Comment by ghost** [comment]
thanks!
